theme = "jetbrains_dark"

[editor]
line-number = "absolute"
mouse = false
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
parents = false
git-ignore = false

[editor.inline-diagnostics]
cursor-line = "error"

[keys.normal]
# Use system clipboard
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"
